#!/bin/bash

### BEGIN INIT INFO
# Provides: Rails_Decuong
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

PROG="start_rails_decuong"

PROG_PATH="/home/su207/decuong-ubuntu" ## Not need, but sometimes helpful (if $PROG resides in /opt for example).

PROG_ARGS=""

PORT_NUMBER=8181

PID_PATH="/home/su207/Auto_start/pid"

LOG_PATH="/home/su207/Auto_start/log"

case "$1" in
 start)
   if [ -e "$(lsof -ti:$PORT_NUMBER)" ]; 
    then 
        kill -9 $(lsof -ti:$PORT_NUMBER)
    else
        echo "$PROG starting"
        su su207 -c $PROG_PATH/$PROG
    fi
   ;;
 stop)
   if [ -e "$(lsof -ti:$PORT_NUMBER)" ]; 
    then
        echo "$PROG stoping"
        kill -9 $(lsof -ti:$PORT_NUMBER)
    else
        echo "$PROG not running"
    fi
    sleep 10
   ;;
 restart)
 if [ -e "$(lsof -ti:$PORT_NUMBER)" ]; 
    then
        kill $(lsof -ti:$PORT_NUMBER)
        sleep 20
        su su207 -c $PROG_PATH/$PROG
    else
        su su207 -c $PROG_PATH/$PROG
    fi
   ;;
 *)
   echo "Usage: $PROG {start|stop|restart}" >&2
   exit 3
   ;;
esac
